// <auto-generated />
using System;
using ExamSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamSys.Models.Migrations
{
    [DbContext(typeof(ExaminationDbContext))]
    partial class ExaminationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamSys.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MaximumDegree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses", t =>
                        {
                            t.HasCheckConstraint("CK_Course_MaximumDegree_Positive", "[MaximumDegree] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 18, 18, 47, 25, 623, DateTimeKind.Utc).AddTicks(3753),
                            Description = "SE Course",
                            IsActive = true,
                            MaximumDegree = 100m,
                            Title = "Software Engineering"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 18, 18, 47, 25, 623, DateTimeKind.Utc).AddTicks(4463),
                            Description = "DB Course",
                            IsActive = true,
                            MaximumDegree = 100m,
                            Title = "Databases"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 9, 18, 18, 47, 25, 623, DateTimeKind.Utc).AddTicks(4466),
                            Description = "Intro",
                            IsActive = true,
                            MaximumDegree = 100m,
                            Title = "Programming Fundamentals"
                        });
                });

            modelBuilder.Entity("ExamSys.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StartDate");

                    b.ToTable("Exams", t =>
                        {
                            t.HasCheckConstraint("CK_Exam_EndAfterStart", "[EndDate] > [StartDate]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Description = "Midterm SE",
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            EndDate = new DateTime(2025, 9, 25, 20, 47, 25, 625, DateTimeKind.Utc).AddTicks(3670),
                            InstructorId = 1,
                            IsActive = true,
                            StartDate = new DateTime(2025, 9, 25, 18, 47, 25, 625, DateTimeKind.Utc).AddTicks(3306),
                            Title = "Midterm SE",
                            TotalMarks = 100m
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Description = "Final DB",
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            EndDate = new DateTime(2025, 9, 28, 21, 47, 25, 625, DateTimeKind.Utc).AddTicks(4897),
                            InstructorId = 2,
                            IsActive = true,
                            StartDate = new DateTime(2025, 9, 28, 18, 47, 25, 625, DateTimeKind.Utc).AddTicks(4894),
                            Title = "Final DB",
                            TotalMarks = 100m
                        });
                });

            modelBuilder.Entity("ExamSys.Models.ExamAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsGraded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSubmitted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StartTime");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamAttempts");
                });

            modelBuilder.Entity("ExamSys.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "smith@example.com",
                            HireDate = new DateTime(2020, 9, 18, 18, 47, 25, 624, DateTimeKind.Utc).AddTicks(8920),
                            IsActive = true,
                            Name = "Dr. Smith",
                            Specialization = "Software Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jones@example.com",
                            HireDate = new DateTime(2022, 9, 18, 18, 47, 25, 624, DateTimeKind.Utc).AddTicks(9766),
                            IsActive = true,
                            Name = "Dr. Jones",
                            Specialization = "Databases"
                        });
                });

            modelBuilder.Entity("ExamSys.Models.InstructorCourse", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("InstructorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("InstructorCourses");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            CourseId = 1,
                            AssignedDate = new DateTime(2025, 9, 18, 18, 47, 25, 626, DateTimeKind.Utc).AddTicks(109),
                            IsActive = true
                        },
                        new
                        {
                            InstructorId = 2,
                            CourseId = 2,
                            AssignedDate = new DateTime(2025, 9, 18, 18, 47, 25, 626, DateTimeKind.Utc).AddTicks(792),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ExamSys.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<decimal>("Marks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuestionDiscriminator")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions", t =>
                        {
                            t.HasCheckConstraint("CK_Question_Marks_Positive", "[Marks] > 0");
                        });

                    b.HasDiscriminator<int>("QuestionDiscriminator");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 18, 18, 47, 25, 625, DateTimeKind.Utc).AddTicks(5193),
                            ExamId = 1,
                            Marks = 10m,
                            QuestionDiscriminator = 0,
                            QuestionText = "What is OOP?",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 18, 18, 47, 25, 625, DateTimeKind.Utc).AddTicks(6496),
                            ExamId = 1,
                            Marks = 5m,
                            QuestionDiscriminator = 1,
                            QuestionText = "SQL is a programming language?",
                            QuestionType = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 9, 18, 18, 47, 25, 625, DateTimeKind.Utc).AddTicks(7424),
                            ExamId = 2,
                            Marks = 20m,
                            QuestionDiscriminator = 2,
                            QuestionText = "Discuss normalization.",
                            QuestionType = 2
                        });
                });

            modelBuilder.Entity("ExamSys.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            EnrollmentDate = new DateTime(2025, 9, 18, 18, 47, 25, 624, DateTimeKind.Utc).AddTicks(5177),
                            IsActive = true,
                            Name = "Alice",
                            StudentNumber = "S1001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            EnrollmentDate = new DateTime(2025, 9, 18, 18, 47, 25, 624, DateTimeKind.Utc).AddTicks(5875),
                            IsActive = true,
                            Name = "Bob",
                            StudentNumber = "S1002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            EnrollmentDate = new DateTime(2025, 9, 18, 18, 47, 25, 624, DateTimeKind.Utc).AddTicks(5920),
                            IsActive = true,
                            Name = "Charlie",
                            StudentNumber = "S1003"
                        },
                        new
                        {
                            Id = 4,
                            Email = "diana@example.com",
                            EnrollmentDate = new DateTime(2025, 9, 18, 18, 47, 25, 624, DateTimeKind.Utc).AddTicks(5923),
                            IsActive = true,
                            Name = "Diana",
                            StudentNumber = "S1004"
                        },
                        new
                        {
                            Id = 5,
                            Email = "eve@example.com",
                            EnrollmentDate = new DateTime(2025, 9, 18, 18, 47, 25, 624, DateTimeKind.Utc).AddTicks(5925),
                            IsActive = true,
                            Name = "Eve",
                            StudentNumber = "S1005"
                        });
                });

            modelBuilder.Entity("ExamSys.Models.StudentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool?>("BooleanAnswer")
                        .HasColumnType("bit");

                    b.Property<int>("ExamAttemptId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MarksObtained")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOption")
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExamAttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("StudentAnswers");
                });

            modelBuilder.Entity("ExamSys.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2025, 9, 18, 18, 47, 25, 625, DateTimeKind.Utc).AddTicks(9160),
                            IsCompleted = false
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2025, 9, 18, 18, 47, 25, 625, DateTimeKind.Utc).AddTicks(9982),
                            IsCompleted = false
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2025, 9, 18, 18, 47, 25, 625, DateTimeKind.Utc).AddTicks(9984),
                            IsCompleted = false
                        });
                });

            modelBuilder.Entity("ExamSys.Models.EssayQuestion", b =>
                {
                    b.HasBaseType("ExamSys.Models.Question");

                    b.Property<string>("GradingCriteria")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("MaxWordCount")
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Question_Marks_Positive", "[Marks] > 0");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("ExamSys.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasBaseType("ExamSys.Models.Question");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Question_Marks_Positive", "[Marks] > 0");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("ExamSys.Models.TrueFalseQuestion", b =>
                {
                    b.HasBaseType("ExamSys.Models.Question");

                    b.Property<bool>("CorrectAnswer")
                        .HasColumnType("bit");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Question_Marks_Positive", "[Marks] > 0");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ExamSys.Models.Exam", b =>
                {
                    b.HasOne("ExamSys.Models.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamSys.Models.Instructor", "Instructor")
                        .WithMany("Exams")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ExamSys.Models.ExamAttempt", b =>
                {
                    b.HasOne("ExamSys.Models.Exam", "Exam")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamSys.Models.Student", "Student")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExamSys.Models.InstructorCourse", b =>
                {
                    b.HasOne("ExamSys.Models.Course", "Course")
                        .WithMany("InstructorCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamSys.Models.Instructor", "Instructor")
                        .WithMany("InstructorCourses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ExamSys.Models.Question", b =>
                {
                    b.HasOne("ExamSys.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ExamSys.Models.StudentAnswer", b =>
                {
                    b.HasOne("ExamSys.Models.ExamAttempt", "ExamAttempt")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamSys.Models.Question", "Question")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamAttempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExamSys.Models.StudentCourse", b =>
                {
                    b.HasOne("ExamSys.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamSys.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExamSys.Models.Course", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("InstructorCourses");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("ExamSys.Models.Exam", b =>
                {
                    b.Navigation("ExamAttempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ExamSys.Models.ExamAttempt", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("ExamSys.Models.Instructor", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("InstructorCourses");
                });

            modelBuilder.Entity("ExamSys.Models.Question", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("ExamSys.Models.Student", b =>
                {
                    b.Navigation("ExamAttempts");

                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
